// Generated by CoffeeScript 2.7.0
import {
  div,
  mount
} from "https://cdn.jsdelivr.net/gh/sigmentjs/sigment-ng@1.3.4/dist/index.js";

import './index.css';

//import styles from './hello.module.css'; # does not execute
mount("app", div({}, div({}, 'Hallo from Sigment'), div({
  class: 'hi'
}, 'four')));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiXFwiLCJzb3VyY2VzIjpbImluZGV4LmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEsT0FBQTtFQUFTLEdBQVQ7RUFBYyxLQUFkO0NBQUEsTUFBQTs7QUFFQSxPQUFBLGNBRkE7OztBQUtBLEtBQUEsQ0FBTSxLQUFOLEVBQ0MsR0FBQSxDQUFJLENBQUEsQ0FBSixFQUNDLEdBQUEsQ0FBSSxDQUFBLENBQUosRUFDQyxvQkFERCxDQURELEVBR0MsR0FBQSxDQUFJO0VBQUEsS0FBQSxFQUFPO0FBQVAsQ0FBSixFQUNDLE1BREQsQ0FIRCxDQUREIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IHsgZGl2LCBtb3VudCB9IGZyb20gXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvZ2gvc2lnbWVudGpzL3NpZ21lbnQtbmdAMS4zLjQvZGlzdC9pbmRleC5qc1wiXHJcblxyXG5pbXBvcnQgJy4vaW5kZXguY3NzJyAjIGRvZXMgbm90IGV4ZWN1dGVcclxuI2ltcG9ydCBzdHlsZXMgZnJvbSAnLi9oZWxsby5tb2R1bGUuY3NzJzsgIyBkb2VzIG5vdCBleGVjdXRlXHJcblxyXG5tb3VudCBcImFwcFwiLCBcclxuXHRkaXYge30sIFxyXG5cdFx0ZGl2IHt9LFxyXG5cdFx0XHQnSGFsbG8gZnJvbSBTaWdtZW50JywgXHJcblx0XHRkaXYgY2xhc3M6ICdoaScsXHJcblx0XHRcdCdmb3VyJ1xyXG4iXX0=
//# sourceURL=c:\github\2026\004-sigment\index.coffee