// Generated by CoffeeScript 2.7.0
var App;

import {
  createSignal,
  div,
  button,
  h1,
  p,
  mount
} from "https://cdn.jsdelivr.net/gh/sigmentjs/sigment-ng@1.3.4/dist/index.js";

// import styles from './hello.module.css'; # fungerar ej
// import './hello.css' # fungerar ej
App = function() {
  return div({
    class: 'hi'
  }, div({
    class: 'hix'
  }, 'Hallå från Sigment'), div({
    class: 'hix'
  }, 'fyran'));
};

mount("app", App());

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiXFwiLCJzb3VyY2VzIjpbImluZGV4LmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEsSUFBQTs7QUFBQSxPQUFBO0VBQVMsWUFBVDtFQUF3QixHQUF4QjtFQUE2QixNQUE3QjtFQUFzQyxFQUF0QztFQUEyQyxDQUEzQztFQUE4QyxLQUE5QztDQUFBLE1BQUEsdUVBQUE7Ozs7QUFLQSxHQUFBLEdBQU0sUUFBQSxDQUFBLENBQUE7U0FDTCxHQUFBLENBQUk7SUFBQyxLQUFBLEVBQU87RUFBUixDQUFKLEVBQ0MsR0FBQSxDQUFJO0lBQUMsS0FBQSxFQUFPO0VBQVIsQ0FBSixFQUNDLG9CQURELENBREQsRUFHQyxHQUFBLENBQUk7SUFBQyxLQUFBLEVBQU87RUFBUixDQUFKLEVBQ0MsT0FERCxDQUhEO0FBREs7O0FBT04sS0FBQSxDQUFNLEtBQU4sRUFBYSxHQUFBLENBQUEsQ0FBYiIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCB7IGNyZWF0ZVNpZ25hbCAsIGRpdiwgYnV0dG9uICwgaDEgLCBwLCBtb3VudCB9IGZyb20gXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvZ2gvc2lnbWVudGpzL3NpZ21lbnQtbmdAMS4zLjQvZGlzdC9pbmRleC5qc1wiXHJcblxyXG4jIGltcG9ydCBzdHlsZXMgZnJvbSAnLi9oZWxsby5tb2R1bGUuY3NzJzsgIyBmdW5nZXJhciBlalxyXG4jIGltcG9ydCAnLi9oZWxsby5jc3MnICMgZnVuZ2VyYXIgZWpcclxuXHJcbkFwcCA9IC0+XHJcblx0ZGl2IHtjbGFzczogJ2hpJ30sXHJcblx0XHRkaXYge2NsYXNzOiAnaGl4J30sXHJcblx0XHRcdCdIYWxsw6UgZnLDpW4gU2lnbWVudCcsXHJcblx0XHRkaXYge2NsYXNzOiAnaGl4J30sXHJcblx0XHRcdCdmeXJhbidcclxuXHRcclxubW91bnQgXCJhcHBcIiwgQXBwKCkiXX0=
//# sourceURL=c:\github\2026\004-sigment\index.coffee