// Generated by CoffeeScript 2.7.0
export default {
  fnt600: {
    style: "color: red"
  }
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibW9kdWxlLmpzIiwic291cmNlUm9vdCI6IlxcIiwic291cmNlcyI6WyJtb2R1bGUuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSxPQUFBLFFBQWU7RUFDWCxNQUFBLEVBQVE7SUFDTixLQUFBLEVBQU87RUFERDtBQURHIiwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0IGRlZmF1bHQge1xyXG4gICAgZm50NjAwOiB7XHJcbiAgICAgIHN0eWxlOiBcImNvbG9yOiByZWRcIjtcclxuICAgIH1cclxuICB9XHJcblxyXG4iXX0=
//# sourceURL=c:\github\2026\004-sigment\module.coffee