// Generated by CoffeeScript 2.7.0
(function() {
  // eml_trees.coffee
  // Rena EML-träd:
  //   S -> 1 | x | eml(S,S) | add(S,S) | mul(S,S) | div(S,S)

  // Inga numeriska serier.
  // Inga vanliga +, -, *, / som definitioner av funktioner.
  // Bara evaluation av trädet använder JS Math.exp / Math.log,
  // eftersom det är själva semantiken för eml.
  var A, Add, Complex, D, Div, E, EPS, Eml, M, Mul, One, Var, addTree, approx, asComplex, assertApprox, assertComplexApprox, assertEqual, assertTrue, complexExp, complexLog, complexSub, countNodes, divTree, eTree, evalTree, evalTreeComplex, expTree, expandTree, lnTree, mulTree, negTree, piTree, runTest, runTests, sinTree, subTree, test_add, test_arithmetic_structure, test_div, test_e, test_exp, test_ln, test_mul, test_pi, test_sin, test_zero, toString, zeroTree;

  EPS = 1e-10;

  // ------------------------------------------------------------
  // Trädnoder
  // ------------------------------------------------------------
  One = function() {
    return {
      kind: 'one'
    };
  };

  Var = function(name) {
    return {
      kind: 'var',
      name
    };
  };

  Eml = function(a, b) {
    return {
      kind: 'eml',
      a,
      b
    };
  };

  Add = function(a, b) {
    return {
      kind: 'add',
      a,
      b
    };
  };

  Mul = function(a, b) {
    return {
      kind: 'mul',
      a,
      b
    };
  };

  Div = function(a, b) {
    return {
      kind: 'div',
      a,
      b
    };
  };

  // kompakta alias
  E = Eml;

  A = Add;

  M = Mul;

  D = Div;

  // ------------------------------------------------------------
  // Evaluering
  // ------------------------------------------------------------
  evalTree = function(node, env = {}) {
    var x, y;
    switch (node.kind) {
      case 'one':
        return 1.0;
      case 'var':
        if (!Object.prototype.hasOwnProperty.call(env, node.name)) {
          throw new Error(`saknar variabel ${node.name}`);
        }
        return env[node.name];
      case 'eml':
        x = evalTree(node.a, env);
        y = evalTree(node.b, env);
        if (y < 0) {
          throw new Error(`eml kräver icke-negativt andra argument, fick ${y}`);
        }
        return Math.exp(x) - Math.log(y);
      case 'add':
        return evalTree(addTree(node.a, node.b), env);
      case 'mul':
        return evalTree(mulTree(node.a, node.b), env);
      case 'div':
        y = evalTree(node.b, env);
        if (y === 0) {
          throw new Error("division med noll");
        }
        return evalTree(divTree(node.a, node.b), env);
      default:
        throw new Error(`okänd nodtyp ${node.kind}`);
    }
  };

  Complex = function(re, im = 0) {
    return {re, im};
  };

  asComplex = function(value) {
    if (typeof value === 'number') {
      return Complex(value, 0);
    } else {
      return value;
    }
  };

  complexSub = function(a, b) {
    a = asComplex(a);
    b = asComplex(b);
    return Complex(a.re - b.re, a.im - b.im);
  };

  complexExp = function(z) {
    var r;
    z = asComplex(z);
    r = Math.exp(z.re);
    if (z.im === 0) {
      return Complex(r, 0);
    }
    return Complex(r * Math.cos(z.im), r * Math.sin(z.im));
  };

  complexLog = function(z) {
    z = asComplex(z);
    return Complex(Math.log(Math.hypot(z.re, z.im)), Math.atan2(z.im, z.re));
  };

  evalTreeComplex = function(node, env = {}) {
    var x, y;
    switch (node.kind) {
      case 'one':
        return Complex(1, 0);
      case 'var':
        if (!Object.prototype.hasOwnProperty.call(env, node.name)) {
          throw new Error(`saknar variabel ${node.name}`);
        }
        return asComplex(env[node.name]);
      case 'eml':
        x = evalTreeComplex(node.a, env);
        y = evalTreeComplex(node.b, env);
        return complexSub(complexExp(x), complexLog(y));
      case 'add':
        return evalTreeComplex(addTree(node.a, node.b), env);
      case 'mul':
        return evalTreeComplex(mulTree(node.a, node.b), env);
      case 'div':
        return evalTreeComplex(divTree(node.a, node.b), env);
      default:
        throw new Error(`okänd nodtyp ${node.kind}`);
    }
  };

  // ------------------------------------------------------------
  // Pretty printer
  // ------------------------------------------------------------
  toString = function(node) {
    switch (node.kind) {
      case 'one':
        return '1';
      case 'var':
        return node.name;
      case 'eml':
        return `E(${toString(node.a)},${toString(node.b)})`;
      case 'add':
        return `+(${toString(node.a)},${toString(node.b)})`;
      case 'mul':
        return `*(${toString(node.a)},${toString(node.b)})`;
      case 'div':
        return `/(${toString(node.a)},${toString(node.b)})`;
      default:
        return '?';
    }
  };

  countNodes = function(node) {
    switch (node.kind) {
      case 'one':
      case 'var':
        return 1;
      case 'eml':
      case 'add':
      case 'mul':
      case 'div':
        return 1 + countNodes(node.a) + countNodes(node.b);
      default:
        throw new Error(`okänd nodtyp ${node.kind}`);
    }
  };

  expandTree = function(node) {
    switch (node.kind) {
      case 'one':
        return One();
      case 'var':
        return Var(node.name);
      case 'eml':
        return E(expandTree(node.a), expandTree(node.b));
      case 'add':
        return expandTree(addTree(node.a, node.b));
      case 'mul':
        return expandTree(mulTree(node.a, node.b));
      case 'div':
        return expandTree(divTree(node.a, node.b));
      default:
        throw new Error(`okänd nodtyp ${node.kind}`);
    }
  };

  // ------------------------------------------------------------
  // Exakta EML-konstruktioner
  // ------------------------------------------------------------

  // exp(x) = eml(x, 1)
  expTree = function(x) {
    return E(x, One());
  };

  // e = eml(1,1)
  eTree = function() {
    return E(One(), One());
  };

  // ln(x) = eml(1, eml(eml(1,x),1))
  lnTree = function(x) {
    return E(One(), E(E(One(), x), One()));
  };

  // 0 = ln(1)
  zeroTree = function() {
    return lnTree(One());
  };

  // a - b = eml(ln(a), exp(b))
  subTree = function(a, b) {
    return E(lnTree(a), expTree(b));
  };

  // -x = 0 - x
  negTree = function(x) {
    return subTree(zeroTree(), x);
  };

  // a + b = a - (-b)
  addTree = function(a, b) {
    return subTree(a, negTree(b));
  };

  // a * b = exp(ln(a) + ln(b))
  mulTree = function(a, b) {
    return expTree(addTree(lnTree(a), lnTree(b)));
  };

  // a / b = exp(ln(a) - ln(b))
  divTree = function(a, b) {
    return expTree(subTree(lnTree(a), lnTree(b)));
  };

  // sin(x) = (exp(i*x) - exp(-i*x)) / (2*i)
  sinTree = function(x) {
    var denominator, i, numerator, two;
    i = Var('i');
    two = A(One(), One());
    numerator = subTree(expTree(M(i, x)), expTree(M(negTree(i), x)));
    denominator = M(two, i);
    return D(numerator, denominator);
  };

  // pi-trädet från oxieml CLI:
  // E(1,E(E(1,E(E(1,E(E(1,E(1,E(1,1))),1)),E(E(1,1),1))),1))

  // Referensen visar att detta matchar Im ~ pi, dvs den imaginära delen är pi,
  // eftersom konstruktionen använder komplex gren internt. Här på reella tal
  // kan vi inte evaluera ln(-1), så detta träd är främst en exakt symbolisk
  // representation. För ren real evaluering lämnas det oevaluerat.
  piTree = function() {
    return E(One(), E(E(One(), E(E(One(), E(E(One(), E(One(), E(One(), One()))), One())), E(E(One(), One()), One()))), One()));
  };

  
  // ------------------------------------------------------------
  // Hjälp för tester
  // ------------------------------------------------------------
  approx = function(a, b, eps = EPS) {
    return Math.abs(a - b) <= eps;
  };

  assertApprox = function(name, actual, expected, eps = EPS) {
    var ok;
    ok = approx(actual, expected, eps);
    console.log(`${ok ? 'OK' : 'FAIL'} ${name} actual=${actual} expected=${expected}`);
    if (!ok) {
      throw new Error(`Test failed: ${name}`);
    }
  };

  assertEqual = function(name, actual, expected) {
    var ok;
    ok = actual === expected;
    console.log(`${ok ? 'OK' : 'FAIL'} ${name} actual=${actual} expected=${expected}`);
    if (!ok) {
      throw new Error(`Test failed: ${name}`);
    }
  };

  assertTrue = function(name, cond) {
    console.log(`${cond ? 'OK' : 'FAIL'} ${name}`);
    if (!cond) {
      throw new Error(`Test failed: ${name}`);
    }
  };

  assertComplexApprox = function(name, actual, expected, eps = EPS) {
    var ok;
    ok = approx(actual.re, expected.re, eps) && approx(actual.im, expected.im, eps);
    console.log(`${ok ? 'OK' : 'FAIL'} ${name} actual=${actual.re}+${actual.im}i expected=${expected.re}+${expected.im}i`);
    if (!ok) {
      throw new Error(`Test failed: ${name}`);
    }
  };

  runTest = function(name, fn) {
    console.log(name);
    return fn();
  };

  // ------------------------------------------------------------
  // Tester: 4 per definierad funktion/konstant
  // ------------------------------------------------------------
  test_exp = function() {
    var t, x;
    x = Var('x');
    t = expTree(x);
    assertApprox("exp(0)", evalTree(t, {
      x: 0
    }), 1);
    assertApprox("exp(1)", evalTree(t, {
      x: 1
    }), Math.E);
    assertApprox("exp(2)", evalTree(t, {
      x: 2
    }), Math.exp(2));
    return assertApprox("exp(-1)", evalTree(t, {
      x: -1
    }), Math.exp(-1));
  };

  test_ln = function() {
    var t, x;
    x = Var('x');
    t = lnTree(x);
    assertApprox("ln(1)", evalTree(t, {
      x: 1
    }), 0);
    assertApprox("ln(e)", evalTree(t, {
      x: Math.E
    }), 1);
    assertApprox("ln(2)", evalTree(t, {
      x: 2
    }), Math.log(2));
    return assertApprox("ln(0.5)", evalTree(t, {
      x: 0.5
    }), Math.log(0.5));
  };

  test_e = function() {
    var t;
    t = eTree();
    assertApprox("e value", evalTree(t), Math.E);
    assertApprox("e > 2", evalTree(t), Math.E);
    assertTrue("e > 2", evalTree(t) > 2);
    return assertTrue("e < 3", evalTree(t) < 3);
  };

  test_zero = function() {
    var t;
    t = zeroTree();
    assertApprox("zero value", evalTree(t), 0);
    assertApprox("zero + tol", evalTree(t), 0, 1e-12);
    assertTrue("zero == 0", evalTree(t) === 0);
    return assertTrue("zero finite", Number.isFinite(evalTree(t)));
  };

  test_add = function() {
    var t, x, y;
    x = Var('x');
    y = Var('y');
    t = A(x, y);
    assertApprox("add 2+3", evalTree(t, {
      x: 2,
      y: 3
    }), 5);
    assertApprox("add 0+4", evalTree(t, {
      x: 0,
      y: 4
    }), 4);
    assertApprox("add 2+5", evalTree(t, {
      x: 2,
      y: 5
    }), 7);
    assertApprox("add 0.5+0.25", evalTree(t, {
      x: 0.5,
      y: 0.25
    }), 0.75);
    return assertComplexApprox("add via complex eml", evalTreeComplex(t, {
      x: 2,
      y: 3
    }), Complex(5, 0));
  };

  test_mul = function() {
    var t, x, y;
    x = Var('x');
    y = Var('y');
    t = M(x, y);
    assertApprox("mul 2*3", evalTree(t, {
      x: 2,
      y: 3
    }), 6);
    assertApprox("mul 1*7", evalTree(t, {
      x: 1,
      y: 7
    }), 7);
    assertApprox("mul 2*8", evalTree(t, {
      x: 2,
      y: 8
    }), 16);
    assertApprox("mul 4*5", evalTree(t, {
      x: 4,
      y: 5
    }), 20);
    return assertComplexApprox("mul via complex eml", evalTreeComplex(t, {
      x: 2,
      y: 3
    }), Complex(6, 0));
  };

  test_div = function() {
    var t, x, y;
    x = Var('x');
    y = Var('y');
    t = D(x, y);
    assertApprox("div 6/3", evalTree(t, {
      x: 6,
      y: 3
    }), 2);
    assertApprox("div 7/1", evalTree(t, {
      x: 7,
      y: 1
    }), 7);
    assertApprox("div 4/0.5", evalTree(t, {
      x: 4,
      y: 0.5
    }), 8);
    assertApprox("div 2/4", evalTree(t, {
      x: 2,
      y: 4
    }), 0.5);
    return assertComplexApprox("div via complex eml", evalTreeComplex(t, {
      x: 6,
      y: 3
    }), Complex(2, 0));
  };

  test_arithmetic_structure = function() {
    var x, y;
    x = Var('x');
    y = Var('y');
    assertEqual("arithmetic string", toString(D(M(A(One(), x), y), x)), "/(*(+(1,x),y),x)");
    return assertComplexApprox("nested arithmetic via complex eml", evalTreeComplex(D(A(x, One()), y), {
      x: 5,
      y: 3
    }), Complex(2, 0));
  };

  test_sin = function() {
    var env, expanded, t, x;
    x = Var('x');
    t = sinTree(x);
    env = function(value) {
      return {
        x: value,
        i: Complex(0, 1)
      };
    };
    assertEqual("sin exact tree string", toString(t), "/(E(E(1,E(E(1,E(*(i,x),1)),1)),E(E(*(E(E(1,E(E(1,E(1,E(E(1,1),1))),1)),E(i,1)),x),1),1)),*(+(1,1),i))");
    console.log(`sin node count=${countNodes(t)}`);
    expanded = expandTree(t);
    console.log(`sin expanded node count=${countNodes(expanded)}`);
    console.log(`sin expanded tree string=${toString(expanded)}`);
    assertTrue("sin expanded contains only E/1/vars", /^[E1ix(),]+$/.test(toString(expanded)));
    assertComplexApprox("sin(0.5)", evalTreeComplex(t, env(0.5)), Complex(Math.sin(0.5), 0));
    assertComplexApprox("sin(1)", evalTreeComplex(t, env(1)), Complex(Math.sin(1), 0));
    assertComplexApprox("sin(pi/2)", evalTreeComplex(t, env(Math.PI / 2)), Complex(1, 0));
    assertComplexApprox("sin(pi)", evalTreeComplex(t, env(Math.PI)), Complex(0, 0));
    return console.log(`sin numeric sample sin(1)=${evalTreeComplex(t, env(1)).re}`);
  };

  test_pi = function() {
    var s, t, z;
    t = piTree();
    s = toString(t);
    assertEqual("pi string nonempty", s.length > 0, true);
    assertTrue("pi starts with E(", s.slice(0, 2) === 'E(');
    assertTrue("pi contains only E/1 punctuation", /^[E1(),]+$/.test(s));
    assertEqual("pi exact tree string", s, "E(1,E(E(1,E(E(1,E(E(1,E(1,E(1,1))),1)),E(E(1,1),1))),1))");
    z = evalTreeComplex(t);
    assertApprox("pi real part", z.re, 0, 1e-12);
    assertApprox("pi imaginary part", z.im, Math.PI);
    assertTrue("pi numeric finite", Number.isFinite(z.re) && Number.isFinite(z.im));
    return assertApprox("pi absolute value", Math.hypot(z.re, z.im), Math.PI);
  };

  runTests = function() {
    var fn, j, len, name, tests;
    tests = [['test_exp', test_exp], ['test_ln', test_ln], ['test_e', test_e], ['test_zero', test_zero], ['test_add', test_add], ['test_mul', test_mul], ['test_div', test_div], ['test_arithmetic_structure', test_arithmetic_structure], ['test_sin', test_sin], ['test_pi', test_pi]];
    for (j = 0, len = tests.length; j < len; j++) {
      [name, fn] = tests[j];
      runTest(name, fn);
    }
    console.log(`Körda testblock: ${((function() {
      var k, len1, results;
      results = [];
      for (k = 0, len1 = tests.length; k < len1; k++) {
        [name] = tests[k];
        results.push(name);
      }
      return results;
    })()).join(', ')}`);
    return console.log("Alla definierade rena EML-träd passerade.");
  };

  runTests();

}).call(this);
