// Generated by CoffeeScript 2.7.0
// Tar emot ett trÃ¤d eller en lista av rÃ¶tter och ser till att alla noder
// fÃ¥r en children-lista, sÃ¥ resten av koden kan traversera utan specialfall.
var applyReducer, executeNode, formatState, matchesExpected, normalizeNode, normalizeTree, resolveStepReducer;

normalizeTree = function(tree) {
  if (Array.isArray(tree)) {
    return tree.map(normalizeNode);
  } else if ((tree != null) && typeof tree === "object") {
    return [normalizeNode(tree)];
  } else {
    throw new Error("Expected test tree to be an object or array");
  }
};

// Bygger om en nod rekursivt till den interna standardformen.
// Det gÃ¶r testmotorn tolerant mot att children saknas i testdatan.
normalizeNode = function(node) {
  var ref;
  return {
    ...node,
    children: ((ref = node.children) != null ? ref : []).map(normalizeNode)
  };
};

// JÃ¤mfÃ¶r actual mot expected som en delmÃ¤ngd.
// Om expected bara innehÃ¥ller vissa fÃ¤lt, ignoreras resten av actual.
matchesExpected = function(actual, expected) {
  if (expected === null || typeof expected !== "object") {
    return Object.is(actual, expected);
  }
  if (Array.isArray(expected)) {
    if (!(Array.isArray(actual) && actual.length === expected.length)) {
      return false;
    }
    return expected.every(function(value, index) {
      return matchesExpected(actual[index], value);
    });
  }
  if (!((actual != null) && typeof actual === "object")) {
    return false;
  }
  return Object.keys(expected).every(function(key) {
    return matchesExpected(actual[key], expected[key]);
  });
};

// HjÃ¤lpfunktion fÃ¶r felmeddelanden sÃ¥ att state skrivs konsekvent.
formatState = function(value) {
  return JSON.stringify(value);
};

// Normaliserar ett steg i en operator-kedja till en kÃ¶rbar reducerfunktion.
resolveStepReducer = function(step) {
  if (typeof step === "function" && (step.reducer != null)) {
    return step.reducer;
  }
  if (typeof step === "function") {
    return step;
  }
  throw new Error(`Invalid reducer step: ${formatState(step)}`);
};

// KÃ¶r antingen en enkel reducer eller en kedja av reducers.
applyReducer = function(reducer, state) {
  if (Array.isArray(reducer)) {
    return reducer.reduce(function(currentState, step) {
      return resolveStepReducer(step)(currentState);
    }, state);
  } else {
    return resolveStepReducer(reducer)(state);
  }
};

// KÃ¶r en nod i trÃ¤det.
// "test"-noden sÃ¤tter start-state, Ã¶vriga noder kÃ¶r sin egen reducer pÃ¥
// fÃ¶rÃ¤lderns state. Resultatet verifieras och skickas sedan vidare till barnen.
executeNode = function(node, parentState, path, failures, context) {
  var actualState, callNumber, child, i, len, message, nextPath, pathLabel, ref, results;
  nextPath = [...path, node.name];
  pathLabel = nextPath.join(" > ");
  callNumber = context.callCount += 1;
  actualState = parentState;
  if (node.name.toLowerCase() === "test") {
    actualState = node.expected;
  } else {
    if (node.reducer == null) {
      throw new Error(`Reducer \"${node.name}\" not found`);
    }
    actualState = applyReducer(node.reducer, parentState);
  }
  if (!matchesExpected(actualState, node.expected)) {
    message = `Assert failed at call ${callNumber} (${pathLabel}): expected ${formatState(node.expected)}, got ${formatState(actualState)}`;
    failures.push(message);
    console.assert(false, message);
  }
  ref = node.children;
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    child = ref[i];
    results.push(executeNode(child, actualState, nextPath, failures, context));
  }
  return results;
};

// Publik entrypoint.
// KÃ¶r hela trÃ¤det uppifrÃ¥n och ned, samlar alla fel och returnerar bÃ¥de trÃ¤det
// och listan med assertion-fel fÃ¶r vidare anvÃ¤ndning.
export var testReducer = function(script) {
  var context, failures, i, len, node, tree;
  tree = normalizeTree(script);
  failures = [];
  context = {
    callCount: 0
  };
  for (i = 0, len = tree.length; i < len; i++) {
    node = tree[i];
    executeNode(node, null, [], failures, context);
  }
  if (failures.length === 0) {
    console.log(`All assertions passed (${tree.length} root test${tree.length === 1 ? "" : "s"}).`);
  }
  return {tree, failures};
};

export var node = function(name, reducer = null) {
  var definition;
  definition = function(expected, ...children) {
    return {name, reducer, expected, children};
  };
  definition.reducer = reducer;
  definition.nodeName = name;
  return definition;
};
